### ISSUE TITLE
[BUG] QR Code reader doesn't launch

### ISSUE THREAD

**Issue by thismachinechills** [msfjarvis/viscerion#189]
**Describe the bug**
In the Android app, tapping the Create button and choosing Create From QR Code doesn't launch the QR code reader. 

**To Reproduce**
1. Install Viscerion from Github releases or the Play Store
2. Launch the app
3. Click Create
4. Choose Create From QR Code

**Expected behavior**
A QR code reader app would launch.

**Screenshots**
N/A

**Device information (please complete the following information):**
 - Device: Moto X
 - OS: Stock Android 9.0, not rooted
 - Backend: Userspace
 - Version: 5.2.3

Also tried with LineageOS 16.0 device and had the same result.

**Additional context**
Nothing relevant found with `adb logcat`

**Comment by msfjarvis** [comment]
I've released [v5.2.4](https://github.com/msfjarvis/viscerion/releases/tag/5.2.4) with the fix on the Play Store. Thanks for reporting and helping make the app better!

**Comment by msfjarvis** [comment]
@all-contributors please add @thismachinechills for bug

**Comment by thismachinechills** [comment]
Thanks for the quick fix! Unfortunately, I'm still running into bugs with a stock Android 9.0 device and a LineageOS 16.0 device.

Selecting Create from QR Code launches an activity, however it crashes. This time `adb logcat` has pertinent information

```
10-19 14:59:41.263  1130  1130 D SurfaceFlinger: duplicate layer name: changing me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity to me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity#2
10-19 14:59:41.316  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.316  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.326  1130  1130 D SurfaceFlinger: duplicate layer name: changing Dim Layer for - Task=5702 to Dim Layer for - Task=5702#1
10-19 14:59:41.326  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.326  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.343  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.343  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.347  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.347  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.350 14525 14525 I Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
--
--
10-19 14:59:41.326  1130  1130 D SurfaceFlinger: duplicate layer name: changing Dim Layer for - Task=5702 to Dim Layer for - Task=5702#1
10-19 14:59:41.326  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.326  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.343  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.343  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.347  1273  3885 V CameraService: supportsCameraApi: for camera ID = 0
10-19 14:59:41.347  1273  3885 V CameraService: supportsCameraApi: Camera id 0 uses HAL3.2 or newer, supports api1/api2 directly
10-19 14:59:41.350 14525 14525 I Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
10-19 14:59:41.359 14525 14525 D AndroidRuntime: Shutting down VM
10-19 14:59:41.366 14525 14525 E AndroidRuntime: FATAL EXCEPTION: main
10-19 14:59:41.366 14525 14525 E AndroidRuntime: Process: me.msfjarvis.viscerion, PID: 14525
10-19 14:59:41.366 14525 14525 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "androidx.camera.core.UseCase$EventListener androidx.camera.core.UseCaseEventConfig.getUseCaseEventListener(androidx.camera.core.UseCase$EventListener)"
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView.startPreview(BarcodeView.kt:65)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView.access$startPreview(BarcodeView.kt:1)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView$bindToLifecycle$1.run(BarcodeView.kt:1)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6912)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
--
--
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView.startPreview(BarcodeView.kt:65)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView.access$startPreview(BarcodeView.kt:1)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.kroegerama.kaiteki.bcode.views.BarcodeView$bindToLifecycle$1.run(BarcodeView.kt:1)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6912)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-19 14:59:41.366 14525 14525 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to set client state on removed layer: me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity#1
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=5702#0
--
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=5702#0
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to destroy on removed layer: me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity#1
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=5702#0
--
10-19 14:59:41.385  1130  1195 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=5702#0
10-19 14:59:41.393  1857  2592 W ActivityManager:   Force finishing activity me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity
10-19 14:59:41.559  1857  1938 W ActivityManager: Exception when unbinding service me.msfjarvis.viscerion/com.wireguard.android.backend.GoBackend$VpnService
10-19 14:59:41.562  1857  4609 I WindowManager: WIN DEATH: Window{cb781f7 u0 me.msfjarvis.viscerion/com.wireguard.android.activity.MainActivity}
10-19 14:59:41.562  1857  4609 I chatty  : uid=1000(system) Binder:1857_17 expire 1 line
--
10-19 14:59:41.562  1857  4609 I chatty  : uid=1000(system) Binder:1857_17 expire 1 line
10-19 14:59:41.563  1857  4155 I ActivityManager: Process me.msfjarvis.viscerion (pid 14525) has died: vis  TOP

```

**Comment by msfjarvis** [comment]
> Thanks for the quick fix! Unfortunately, I'm still running into bugs with a stock Android 9.0 device and a LineageOS 16.0 device.

Yeah it ended up being a problem with the release builds configuration and I only tested with debug... v5.2.5 is up on the Play Store and fixes the bug on my devices. I'll re-open this until you can confirm.

**Comment by thismachinechills** [comment]
Awesome, works on my end. Thanks again!
